version: "3.9"

services:
  redmine-mattermost-bridge:
    image: "python:latest"
    restart: "unless-stopped"
    working_dir: "/app"
    ports:
      - "8090:8090"

    env_file:
      - ".docker.env"
    environment:
      MATTERMOST_SITEURL: "http://mattermost:8065"

    volumes:
      - "./:/app"

    command: >
      bash -c 'pip3 install -r requirements.txt &&  python3 my_app.py'

    networks:
      dev:
        ipv4_address: 172.10.1.50

networks:
  dev:
    external: true

