version: '3.9'

services:
  redmine:
    build:
      context: .
    image: redmine
    ports:
      - "3000:3000"

    volumes:
      - ./storage/docker_redmine-plugins:/usr/src/redmine/plugins
      - ./storage/docker_redmine-themes:/usr/src/redmine/public/themes
      - ./storage/docker_redmine-data:/usr/src/redmine/files
      - ./storage/configuration.yml:/usr/src/redmine/config/configuration.yml

    environment:
      REDMINE_DB_POSTGRES: "postgres"
      REDMINE_DB_USERNAME: "postgres"
      REDMINE_DB_PASSWORD: "strong_pass"
      REDMINE_DB_DATABASE: "redmine"
      REDMINE_SECRET_KEY_BASE: "…"
    restart: "unless-stopped"

    networks:
      dev:
        ipv4_address: 172.10.1.10

  postgres:
    image: postgres
    volumes:
      - ./storage/postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "strong_pass"
      POSTGRES_DB: "redmine"
      PGDATA: "/var/lib/postgresql/data"
    restart: "unless-stopped"
    ports:
      - "50002:50002"

    networks:
      dev:
        ipv4_address: 172.10.1.20


networks:
  dev:
    external: true


